os: osx
osx_image: xcode10.3
language: swift
install:
    - brew install mint
    - bundle install
    - mint install swiftlint
script:
    - bundle exec fastlane tests
    - bundle exec fastlane lint